# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ski_conditions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ski_conditions.proto\">\n\x19SkiConditionsSubscription\x12\x0f\n\x07resorts\x18\x01 \x03(\t\x12\x10\n\x08\x63lientID\x18\x02 \x01(\x05\"\x81\x01\n\nConditions\x12\x0e\n\x06resort\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x12\n\nwind_speed\x18\x03 \x01(\x02\x12\x10\n\x08is_night\x18\x04 \x01(\x08\x12\x11\n\x03sky\x18\x05 \x03(\x0b\x32\x04.Sky\x12\x15\n\x05slope\x18\x06 \x03(\x0b\x32\x06.Slope\"E\n\x03Sky\x12\x17\n\x06\x63louds\x18\x01 \x01(\x0e\x32\x07.Clouds\x12%\n\rprecipitation\x18\x02 \x01(\x0e\x32\x0e.Precipitation\"0\n\x05Slope\x12\x12\n\nsnow_level\x18\x01 \x01(\x05\x12\x13\n\x04snow\x18\x02 \x01(\x0e\x32\x05.Snow*;\n\rPrecipitation\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08SNOWFALL\x10\x01\x12\x08\n\x04RAIN\x10\x02\x12\x08\n\x04HAIL\x10\x03*X\n\x06\x43louds\x12\t\n\x05\x43LEAR\x10\x00\x12\x0e\n\nFEW_CLOUDS\x10\x01\x12\x14\n\x10PARTIALLY_CLOUDY\x10\x02\x12\n\n\x06\x43LOUDY\x10\x03\x12\x11\n\rFULLY_CLOUDED\x10\x04*P\n\x04Snow\x12\x11\n\rCORDUROY_SNOW\x10\x00\x12\n\n\x06POWDER\x10\x01\x12\x07\n\x03ICE\x10\x02\x12\x0c\n\x08WET_SNOW\x10\x03\x12\x12\n\x0e\x43OMPACTED_SNOW\x10\x04\x32T\n\rSkiConditions\x12\x43\n\x16SubscribeSkiConditions\x12\x1a.SkiConditionsSubscription\x1a\x0b.Conditions0\x01\x42\x1b\n\x03genB\x12SkiConditionsProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ski_conditions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\003genB\022SkiConditionsProtoP\001'
  _PRECIPITATION._serialized_start=341
  _PRECIPITATION._serialized_end=400
  _CLOUDS._serialized_start=402
  _CLOUDS._serialized_end=490
  _SNOW._serialized_start=492
  _SNOW._serialized_end=572
  _SKICONDITIONSSUBSCRIPTION._serialized_start=24
  _SKICONDITIONSSUBSCRIPTION._serialized_end=86
  _CONDITIONS._serialized_start=89
  _CONDITIONS._serialized_end=218
  _SKY._serialized_start=220
  _SKY._serialized_end=289
  _SLOPE._serialized_start=291
  _SLOPE._serialized_end=339
  _SKICONDITIONS._serialized_start=574
  _SKICONDITIONS._serialized_end=658
# @@protoc_insertion_point(module_scope)
