# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ski_conditions_pb2 as ski__conditions__pb2


class SkiConditionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeSkiConditions = channel.unary_stream(
                '/SkiConditions/SubscribeSkiConditions',
                request_serializer=ski__conditions__pb2.SkiConditionsSubscription.SerializeToString,
                response_deserializer=ski__conditions__pb2.Conditions.FromString,
                )


class SkiConditionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubscribeSkiConditions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkiConditionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeSkiConditions': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeSkiConditions,
                    request_deserializer=ski__conditions__pb2.SkiConditionsSubscription.FromString,
                    response_serializer=ski__conditions__pb2.Conditions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SkiConditions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SkiConditions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubscribeSkiConditions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/SkiConditions/SubscribeSkiConditions',
            ski__conditions__pb2.SkiConditionsSubscription.SerializeToString,
            ski__conditions__pb2.Conditions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
